name: weather_app
description: Flutter minimalism weather app


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.8.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.0
  intl: ^0.18.1
  toggle_switch: ^2.1.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  current_location: ^0.0.3
  cupertino_icons: ^1.0.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
